title: Backgammon Network | Blog
description: The latest news from bkgmn.net.
url: https://blog.bkgmn.net
author:
  name: Softwerks LLC
  url: https://www.softwerks.com

include:
  - _pages

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

permalink: /:year-:month-:day/:title
paginate:  5
