title: Backgammon Network | Blog
description: The latest news from www.bkgmn.net.
url: https://blog.bkgmn.net
author: Softwerks LLC

include:
  - _pages

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

permalink: /:year-:month-:day/:title
paginate:  5
