remote_theme: chesterhow/tale

# Site settings
title:          Backgammon Network
description:    "Blog"
baseurl:        "/"
url:            "https://blog.bkgmn.net"

# Author
author:
  name:         Softwerks LLC
  url:          https://www.softwerks.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Gems
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
